name: ci

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ "1.24", "stable" ]

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go-version }}

      - name: Go vet
        run: go vet ./...

      - name: Run Golint
        uses: golangci/golangci-lint-action@v9
        with:
          version: latest

      - name: Test
        run: go test -race ./...
